export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html>
        <header>
            <meta name="google-site-verification" content="rJjd21Egt5wDzuulodMe9LeB3pXRhNPr-aAbDE8mWy8" />
        </header>
        <body>{children}</body>
        </html>
    )
}
